자연어 이해-> 기계가 인간의 언어를 이해 할려는 분야

자연어 생성-> 자연어에 대하여 목적에 맞게 자연어를 생성하는 분야 

#빅데이터의 3요소(3v)

1.volume-데이터의 양

2.variety-데이터의 다양성 -> 정형: 관계형 데이터베이스, 비정형:텍스트,오디오,비디오 등, 반정형:HTML,XML등

3.velocity-데이터의 속도


#토큰화:문장을 토큰(형태소) 단위로 구분하는 작업
1.Bag of word-> 직관적 반면 순서가 고려되지 않음,

vector의 길이가 vocab의 길이만큼 길어질 수 있다.

2.word2vec

3.doc2vec

4.BERT




#자연어 처리를 통해 할 수 있는 것
TTS(text-to-speech),STT(Speech-to-text),챗봇,기계번역,기계독해



#지도학습/비지도학습

지도학습 - 정답이 o: 회귀-날씨 예측 등, 분류: 분류하는거

비지도학습 - 정답이 x:군집화-비슷한거끼리 묶음, 이상치 탐지-위조화폐 찾기 등

#머신러닝 관련 라이브러리

데이터 이해&전처리

1.numpy - 통계치, 선형대수 수치 계산

2.pandas - 데이터프레임 테이블 형태

3.Matplotlib - 데이터 시각화

머신러닝

1.전통적인 머신러닝(Scikit-learn)

2.딥러닝 지도학습(TensorFlow/pyTorch)


#Bag of words
Cosine Similarity(유사도 검사) -> -1~1의 값을 가지고 있다. 1의 가까울수도 두 벡터는 유사하다 판단

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
#"나는 서울에 산다"[1,1,1,0,1,1,0] 
sent1 = np.array([1,1,1,0,1,1,0]) #numpy.array로 변경한 이유는 리스트 간의 연산은 어려워 넘파이 배열로 변경
sent1.shape #shape을 보면 7개의 원소가 있고 1차원배열이다

(7,)

In [4]:
#"나 혼자 산다" [1,0,0,1,0,1,0]
sent2 = np.array([1,0,0,1,0,1,0])

In [5]:
#"나는 서울에 있다"[1,1,1,0,1,0,1]
sent3 = np.array([1,1,1,0,1,0,1])


In [8]:
sent1 + sent2

array([2, 1, 1, 1, 1, 2, 0])

In [9]:
[1,1,1,0,1,1,0] + [1,0,0,1,0,1,0] # -> 위와 다르게 리스트를 더하면 합쳐짐

[1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0]

In [12]:
from sklearn.metrics.pairwise import cosine_similarity # sklearn에 있는 consine_simialarity를 사용하기 위한 라이브러리, sklearn.metrics.pairwise 하위 모듈은 유틸리티를 구현하여 쌍별 거리 또는 샘플 집합의 친화도를 평가합니다.
cosine_similarity(sent1.reshape(1,-1),sent2.reshape(1,-1)) #1행 뒤에 있는 값을 불러오기 위해 -1 -> reshape한 이유는 2차원으로 만들어주기 위해서이다.

#결과 값은 sent1과 sent2의 유사도는 아래의 값이다

array([[0.51639778]])

In [14]:
cosine_similarity(sent1.reshape(1,-1),sent3.reshape(1,-1))

array([[0.8]])

In [16]:
def cosine_similarity_1(x,y): #1차원 배열을 넣을꺼다
  return np.dot(x,y) / (np.linalg.norm(x) * np.linalg.norm(y))   # cosin_similarity가 내부적으로 생성하는 방법, 내적하는 함수 이용한거임

In [17]:
cosine_similarity_1(sent1,sent2)

0.5163977794943222

In [18]:
cosine_similarity_1(sent1,sent3)

0.7999999999999998

#단어 빈도 분석과 데이터 소개
빈도 분석: 특정 말뭉치에서 등장한 단어의 빈도를 계산->관심이 많은 키워드를 추출

워드클라우드:빈도의 크기에 비례해서 단어의 크기가 커지도록 시각화


#한글 형태소 분석
KoNLpy 라이브러리에서 Mecab,okt의 성능이 우수함

토큰이 의도하지 않은 대로 구분되기도 한다. - 그런 부분은 사용자가 설정해줘야함

#불용어처리
1.분석에 도움이 되지 않는 형태소는 제거

2.분석 목적에 따라 의미 없는 단얻르을 불영어로 처리할 수 있음


#빈도분석_워드클라우드 실습 전처리